# Generated by Django 4.0.5 on 2022-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('s', 'Stripe')], default='s', max_length=1),
        ),
    ]
