# Generated by Django 4.0.5 on 2022-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_donation_stripe_id_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe')], default='s', max_length=10),
        ),
    ]
