# Generated by Django 4.0.5 on 2022-06-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Make Sure you are careful about this check? If you check this it will mark this transaction as successful verified so if user has paid then you can check this.'),
        ),
    ]
